version: '3.3'
services:
    web:
        build:
              context: ../revisisekian
              dockerfile: Dockerfile
        container_name: php22
        depends_on:
            - db
        volumes:
            - ../revisisekian:/var/www/html/
        ports:
            - 8080:80
    db:
        container_name : mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_trainingcentre
            MYSQL_USER: localhost
            MYSQL_PASSWORD: root
        ports:
           - 6033:3306
                 